### Create an order
POST http://localhost:8080/order
Content-Type: application/json

{
  "price": "150.0",
  "tax": "15.0"
}

### List all orders (REST)
GET http://localhost:8080/order

### List all orders (GraphQL)
POST http://localhost:8082/query
Content-Type: application/json

{
    "query": "query { listOrders { id price tax finalPrice } }"
}