services:
  app:
    build: .
    container_name: list-orders-app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    environment:
      - DB_URL=postgres://user:password@db:5432/ordersdb?sslmode=disable
      - WEB_SERVER_PORT=8080

  db:
    image: postgres:14-alpine
    container_name: list-orders-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ordersdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ordersdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    container_name: list-orders-migrate
    volumes:
      - ./internal/infra/database/migration:/migrations
    command: ["-path", "/migrations", "-database", "postgres://user:password@db:5432/ordersdb?sslmode=disable", "up"]
    depends_on:
      db:
        condition: service_healthy