services:
  app:
    build: .
    container_name: list-orders-app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    environment:
      - VIPER_DB_URL=postgres://user:password@db:5432/ordersdb?sslmode=disable
      - VIPER_RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/

  db:
    image: postgres:14-alpine
    container_name: list-orders-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ordersdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ordersdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    container_name: list-orders-migrate
    volumes:
      - ./internal/infrastructure/database/migration:/migrations
    command: ["-path", "/migrations", "-database", "postgres://user:password@db:5432/ordersdb?sslmode=disable", "up"]
    depends_on:
      db:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: list-orders-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"