version: '3.8'

services:
  app:
    build: .
    container_name: list-orders-challenge-app
    ports:
      - "8080:8080"   # REST API
      - "50051:50051" # gRPC
      - "8082:8082"   # GraphQL
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_DRIVER=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=orders
      - WEB_SERVER_PORT=8080
      - GRPC_SERVER_PORT=50051
      - GRAPHQL_SERVER_PORT=8082

  db:
    image: mysql:5.7
    container_name: list-orders-challenge-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  migrate:
    image: migrate/migrate
    container_name: list-orders-challenge-migrate
    volumes:
      - ./internal/infra/database/sql/migrations:/migrations
    command: ["-path", "/migrations", "-database",  "mysql://root:root@tcp(db:3306)/orders?multiStatements=true", "up"]
    depends_on:
      db:
        condition: service_healthy