services:
  app:
    build: .
    container_name: list-orders-app
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - rabbitmq
    environment:
      # Viper pode sobrescrever o YML com estas variáveis de ambiente.
      - VIPER_DB_URL=postgres://user:password@db:5432/ordersdb?sslmode=disable
      - VIPER_RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/

  db:
    image: postgres:13
    container_name: list-orders-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ordersdb
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: list-orders-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # Porta para a UI de Gerenciamento