// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/gabrielfeb/list-orders-challenge-go/internal/application/usecase"
	"github.com/gabrielfeb/list-orders-challenge-go/internal/infrastructure/database"
	"github.com/gabrielfeb/list-orders-challenge-go/internal/infrastructure/web/handler"
)

// Injectors from wire.go:

func InitializeOrderHandler(db *sql.DB) *handler.OrderHandler {
	orderRepository := database.NewOrderRepository(db)
	createOrderUseCase := usecase.NewCreateOrderUseCase(orderRepository)
	listOrdersUseCase := usecase.NewListOrdersUseCase(orderRepository)
	orderHandler := handler.NewOrderHandler(createOrderUseCase, listOrdersUseCase)
	return orderHandler
}