// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/gabrielfeb/list-orders-challenge-go/internal/application/repository"
	"github.com/gabrielfeb/list-orders-challenge-go/internal/application/usecase"
	"github.com/gabrielfeb/list-orders-challenge-go/internal/infrastructure/database"
	"github.com/gabrielfeb/list-orders-challenge-go/internal/infrastructure/graph"
	"github.com/gabrielfeb/list-orders-challenge-go/internal/infrastructure/web/handler"
)

// Injectors from wire.go:

func InitializeServer(db *sql.DB) (*Server, error) {
	orderRepository := database.NewOrderRepository(db)
	createOrderUseCase := usecase.NewCreateOrderUseCase(orderRepository)
	listOrdersUseCase := usecase.NewListOrdersUseCase(orderRepository)
	orderHandler := handler.NewOrderHandler(createOrderUseCase, listOrdersUseCase)
	resolver := NewGraphQLResolver(createOrderUseCase, listOrdersUseCase)
	server := NewServer(orderHandler, resolver)
	return server, nil
}