// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateOrderInput struct {
	Preco   float64 `json:"preco"`
	Imposto float64 `json:"imposto"`
}

type Mutation struct {
}

type Order struct {
	ID         string  `json:"id"`
	Preco      float64 `json:"preco"`
	Imposto    float64 `json:"imposto"`
	PrecoFinal float64 `json:"precoFinal"`
}

type Query struct {
}
